/**
 * The exact set of IPC channel names the sandboxed preload forwards to the main process. A plain
 * string array with no imports so the preload bundle stays tiny. `ipc.ts` asserts at compile time
 * that this list and the schema registry name the same channels. Push channels the renderer may
 * subscribe to are listed alongside for the same reason.
 */
export const IPC_CHANNELS = [
    'app.info',
    'update.state',
    'update.check',
    'update.download',
    'update.install',
    'startupChecks',
    'contexts.list',
    'context.current',
    'context.set',
    'namespace.set',
    'settings.get',
    'settings.set',
    'kubeconfig.pick',
    'kubeconfig.useDefault',
    'namespaces.list',
    'namespace.active',
    'cluster.active',
    'clusters.list',
    'nodes.list',
    'nodes.get',
    'nodes.cordon',
    'nodes.drainPlan',
    'resources.list',
    'resources.get',
    'pods.logSnapshot',
    'pods.logDownload',
    'pods.owners',
    'workloads.pods',
    'events.forObject',
    'events.recent',
    'events.list',
    'quotas.list',
    'limits.list',
    'metrics.sparklines',
    'metrics.workloadHealth',
    'metrics.alerts',
    'metrics.podSeries',
    'metrics.nodeSeries',
    'metrics.deploymentSeries',
    'deployments.replicaSets',
    'deployments.rollouts',
    'deployments.rolloutStatus',
    'deployments.rollback',
    'deployments.pause',
    'deployments.compare',
    'configMaps.entries',
    'secrets.entries',
    'secrets.reveal',
    'services.ports',
    'services.endpoints',
    'ingresses.rules',
    'releases.list',
    'releases.get',
    'releases.revisions',
    'releases.rollback',
    'releases.uninstall',
    'helmCharts.list',
    'chartRepositories.list',
    'chartRepositories.add',
    'chartRepositories.refresh',
    'chartRepositories.remove',
    'namespaces.detail',
    'customResources.list',
    'customResources.get',
    'customResources.getYaml',
    'resources.meta',
    'resources.related',
    'resources.getYaml',
    'resources.describe',
    'resources.create',
    'resources.replace',
    'resources.delete',
    'resources.scale',
    'resources.restart',
    'pods.evict',
    'jobs.retry',
    'cronJobs.trigger',
    'cronJobs.suspend',
    'autoscalers.update',
] as const;

export const SUBSCRIPTION_CHANNELS = ['update.state', 'open-settings'] as const;

/** Stream channels the preload's `stream()` accepts. Schemas live in `streams.ts`; this file stays import-free. */
export const STREAM_CHANNELS = [
    'resources.watch',
    'pods.logs',
    'pods.exec',
    'pods.portForward',
    'nodes.drain',
] as const;

export type AllowedChannel = (typeof IPC_CHANNELS)[number];
export type AllowedSubscription = (typeof SUBSCRIPTION_CHANNELS)[number];
export type AllowedStream = (typeof STREAM_CHANNELS)[number];
